import { useState } from 'react'

const types = ['Awareness Campaign', 'Tree Plantation', 'Sustainability Drive', 'Cleanliness Drive', 'Rally', 'Workshop', 'Seminar', 'Environmental Program', 'Other']
export default function EventFormModal({ onConfirm, onCancel }) {
  const [form, setForm] = useState({ title: '', eventType: types[0], description: '', location: '', date: '', startTime: '', endTime: '', organizer: '', audience: '', isPublished: true })
  const update = (event) => setForm({ ...form, [event.target.name]: event.target.value })
  const valid = form.title.trim() && form.location.trim() && form.date
  return <div className="modal-overlay"><div className="modal-card modal-card--wide"><h3>Post awareness event</h3><label className="field"><span>Title</span><input name="title" value={form.title} onChange={update} /></label><label className="field"><span>Event type</span><select name="eventType" value={form.eventType} onChange={update}>{types.map((type) => <option key={type}>{type}</option>)}</select></label><label className="field"><span>Description</span><textarea name="description" value={form.description} onChange={update} /></label><div className="field-row"><label className="field"><span>Location</span><input name="location" value={form.location} onChange={update} /></label><label className="field"><span>Date</span><input type="date" name="date" value={form.date} onChange={update} /></label></div><div className="field-row"><label className="field"><span>Start time</span><input type="time" name="startTime" value={form.startTime} onChange={update} /></label><label className="field"><span>End time</span><input type="time" name="endTime" value={form.endTime} onChange={update} /></label></div><label className="field"><span>Organizer</span><input name="organizer" value={form.organizer} onChange={update} /></label><label className="field"><span>Audience</span><input name="audience" value={form.audience} onChange={update} /></label><div className="modal-actions"><button className="btn-ghost" onClick={onCancel}>Cancel</button><button className="btn-primary" disabled={!valid} onClick={() => onConfirm(form)}>Publish event</button></div></div></div>
}
